
"*.6pl",
            "*.6pm",
            "*.asc",
            "*.automount",
            "*.bash",
            "*.bzl",
            "*.C",
            "*.c++",
            "*.cc",
            "*.cfg",
            "*.cp",
            "*.CPP",
            "*.cpp",
            "*.cxx",
            "*.device",
            "*.duby",
            "*.ebuild",
            "*.eclass",
            "*.exheres-0",
            "*.exlib",
            "*.gemspec",
            "*.H",
            "*.h++",
            "*.hh",
            "*.hpp",
            "*.htm.j2",
            "*.htm.jinja2",
            "*.html.j2",
            "*.html.jinja2",
            "*.hxx",
            "*.inf",
            "*.ini",
            "*.jy",
            "*.ksh",
            "*.mount",
            "*.nqp",
            "*.p6",
            "*.p6l",
            "*.p6m",
            "*.path",
            "*.pem",
            "*.pl",
            "*.pl6",
            "*.pm",
            "*.pm6",
            "*.py",
            "*.pyi",
            "*.pyw",
            "*.rake",
            "*.raku",
            "*.rakudoc",
            "*.rakumod",
            "*.rakutest",
            "*.rb",
            "*.rbw",
            "*.rbx",
            "*.sage",
            "*.sc",
            "*.scope",
            "*.service",
            "*.sh",
            "*.slice",
            "*.socket",
            "*.swap",
            "*.t",
            "*.tac",
            "*.target",
            "*.timer",
            "*.tpp",
            "*.vim",
            "*.xhtml.j2",
            "*.xhtml.jinja2",
            "*.zsh",
            ".bash_*",
            ".bashrc",
            ".editorconfig",
            ".exrc",
            ".gvimrc",
            ".kshrc",
            ".vimrc",
            ".zshrc",
            "_exrc",
            "_gvimrc",
            "_vimrc",
            "application/atom+xml",
            "application/javascript",
            "application/mathematica",
            "application/pgp-encrypted",
            "application/pgp-keys",
            "application/pgp-signature",
            "application/rss+xml",
            "application/vnd.wolfram.cdf",
            "application/vnd.wolfram.mathematica",
            "application/vnd.wolfram.mathematica.package",
            "application/x-httpd-lasso",
            "application/x-httpd-lasso[89]",
            "application/x-httpd-php",
            "application/x-httpd-php3",
            "application/x-httpd-php4",
            "application/x-httpd-php5",
            "application/x-javascript",
            "application/x-javascript+cheetah",
            "application/x-javascript+django",
            "application/x-javascript+genshi",
            "application/x-javascript+jinja",
            "application/x-javascript+lasso",
            "application/x-javascript+mako",
            "application/x-javascript+myghty",
            "application/x-javascript+php",
            "application/x-javascript+ruby",
            "application/x-javascript+smarty",
            "application/x-javascript+spitfire",
            "application/xml",
            "application/x-php",
            "application/x-python",
            "application/x-python3",
            "bash_*",
            "bashrc",
            "BUCK",
            "BUILD",
            "BUILD.bazel",
            "Gemfile",
            "gvimrc",
            "id_dsa",
            "id_ecdsa",
            "id_ecdsa_sk",
            "id_ed25519",
            "id_ed25519_sk",
            "id_rsa",
            "image/svg+xml",
            "kshrc",
            "PKGBUILD",
            "Rakefile",
            "SConscript",
            "SConstruct",
            "text/html+lasso",
            "text/javascript",
            "text/javascript+cheetah",
            "text/javascript+django",
            "text/javascript+genshi",
            "text/javascript+jinja",
            "text/javascript+lasso",
            "text/javascript+mako",
            "text/javascript+mygthy",
            "text/javascript+php",
            "text/javascript+ruby",
            "text/javascript+smarty",
            "text/javascript+spitfire",
            "text/S",
            "text/S-plus",
            "text/x-javascript",
            "text/x-javascript+cheetah",
            "text/x-javascript+django",
            "text/x-javascript+genshi",
            "text/x-javascript+jinja",
            "text/x-javascript+lasso",
            "text/x-javascript+mako",
            "text/x-javascript+myghty",
            "text/x-javascript+php",
            "text/x-javascript+ruby",
            "text/x-javascript+smarty",
            "text/x-javascript+spitfire",
            "text/xml",
            "text/x-python",
            "text/x-python3",
            "text/x-R",
            "text/x-r",
            "text/x-r-history",
            "text/x-r-profile",
            "text/x-r-source",
            "Vagrantfile",
            "vimrc",
            "WORKSPACE",
            "zshrc",
        "ABAP",
        "ABNF",
        "ActionScript 3",
        "ActionScript",
        "Ada",
        "ADL",
        "Agda",
        "Aheui",
        "Alloy",
        "AmbientTalk",
        "AMDGPU",
        "Ampl",
        "Angular2",
        "ANSYS parametric design language",
        "ANTLR With ActionScript Target",
        "ANTLR With C# Target",
        "ANTLR With CPP Target",
        "ANTLR With Java Target",
        "ANTLR With ObjectiveC Target",
        "ANTLR With Perl Target",
        "ANTLR With Python Target",
        "ANTLR With Ruby Target",
        "ApacheConf",
        "APL",
        "AppleScript",
        "Arduino",
        "Arrow",
        "Arturo",
        "ASCII armored",
        "AspectJ",
        "aspx-cs",
        "aspx-vb",
        "Asymptote",
        "Augeas",
        "autohotkey",
        "AutoIt",
        "Awk",
        "BARE",
        "Base Makefile",
        "Bash Session",
        "Bash",
        "Batchfile",
        "BBC Basic",
        "BBCode",
        "Bdd",
        "Befunge",
        "Berry",
        "BibTeX",
        "BlitzBasic",
        "BlitzMax",
        "BNF",
        "Boo",
        "Boogie",
        "Brainfuck",
        "BST",
        "BUGS",
        "C",
        "C#",
        "C++",
        "ca65 assembler",
        "cADL",
        "CAmkES",
        "CapDL",
        "Cap'n Proto",
        "Carbon",
        "CBM BASIC V2",
        "CDDL",
        "Ceylon",
        "CFEngine3",
        "cfstatement",
        "ChaiScript",
        "Chapel",
        "Charmci",
        "Cheetah",
        "Cirru",
        "Clay",
        "Clean",
        "Clojure",
        "ClojureScript",
        "CMake",
        "c-objdump",
        "COBOL",
        "COBOLFree",
        "CoffeeScript",
        "Coldfusion CFC",
        "Coldfusion HTML",
        "COMAL-80",
        "Common Lisp",
        "Component Pascal",
        "Coq",
        "cplint",
        "cpp-objdump",
        "CPSA",
        "Crmsh",
        "Croc",
        "Cryptol",
        "Crystal",
        "Csound Document",
        "Csound Orchestra",
        "Csound Score",
        "CSS",
        "CSS+Django/Jinja",
        "CSS+Genshi Text",
        "CSS+Lasso",
        "CSS+Mako",
        "CSS+mozpreproc",
        "CSS+Myghty",
        "CSS+PHP",
        "CSS+Ruby",
        "CSS+Smarty",
        "CSS+UL4",
        "CUDA",
        "Cypher",
        "Cython",
        "D",
        "Darcs Patch",
        "Dart",
        "DASM16",
        "Debian Control file",
        "Debian Sourcelist",
        "Delphi",
        "Devicetree",
        "dg",
        "Diff",
        "Django/Jinja",
        "d-objdump",
        "Docker",
        "DTD",
        "Duel",
        "Dylan session",
        "Dylan",
        "DylanLID",
        "Earl Grey",
        "Easytrieve",
        "EBNF",
        "eC",
        "ECL",
        "Eiffel",
        "Elixir iex session",
        "Elixir",
        "Elm",
        "Elpi",
        "EmacsLisp",
        "E-mail",
        "Embedded Ragel",
        "ERB",
        "Erlang erl session",
        "Erlang",
        "Evoque",
        "execline",
        "Ezhil",
        "F#",
        "Factor",
        "Fancy",
        "Fantom",
        "Felix",
        "Fennel",
        "Fift",
        "Fish",
        "Flatline",
        "FloScript",
        "Forth",
        "Fortran",
        "FortranFixed",
        "FoxPro",
        "Freefem",
        "FStar",
        "FunC",
        "Futhark",
        "GAP session",
        "GAP",
        "GAS",
        "g-code",
        "GDScript",
        "Genshi Text",
        "Genshi",
        "Gettext Catalog",
        "Gherkin",
        "GLSL",
        "Gnuplot",
        "Go",
        "Golo",
        "GoodData-CL",
        "Gosu Template",
        "Gosu",
        "Graphviz",
        "Groff",
        "Groovy",
        "GSQL",
        "Haml",
        "Handlebars",
        "Haskell",
        "Haxe",
        "Hexdump",
        "HLSL",
        "HSAIL",
        "Hspec",
        "HTML + Angular2",
        "HTML",
        "HTML+Cheetah",
        "HTML+Django/Jinja",
        "HTML+Evoque",
        "HTML+Genshi",
        "HTML+Handlebars",
        "HTML+Lasso",
        "HTML+Mako",
        "HTML+Myghty",
        "HTML+PHP",
        "HTML+Smarty",
        "HTML+Twig",
        "HTML+UL4",
        "HTML+Velocity",
        "Hxml",
        "Hy",
        "Hybris",
        "Icon",
        "IDL",
        "Idris",
        "Igor",
        "Inform 6 template",
        "Inform 6",
        "Inform 7",
        "INI",
        "Io",
        "Ioke",
        "IRC logs",
        "Isabelle",
        "JAGS",
        "Jasmin",
        "Java Server Page",
        "Java",
        "JavaScript",
        "JavaScript+Cheetah",
        "JavaScript+Django/Jinja",
        "JavaScript+Genshi Text",
        "JavaScript+Lasso",
        "JavaScript+Mako",
        "Javascript+mozpreproc",
        "JavaScript+Myghty",
        "JavaScript+PHP",
        "JavaScript+Ruby",
        "JavaScript+Smarty",
        "Javascript+UL4",
        "JCL",
        "JMESPath",
        "JSGF",
        "JSLT",
        "JSON",
        "JSONBareObject",
        "JSON-LD",
        "Jsonnet",
        "Julia console",
        "Julia",
        "Juttle",
        "Kal",
        "Kconfig",
        "Kernel log",
        "Koka",
        "Kotlin",
        "Lasso",
        "Lean",
        "LessCss",
        "Lighttpd configuration file",
        "LilyPond",
        "Limbo",
        "liquid",
        "Literate Agda",
        "Literate Cryptol",
        "Literate Haskell",
        "Literate Idris",
        "LiveScript",
        "LLVM",
        "LLVM-MIR Body",
        "LLVM-MIR",
        "Logos",
        "Logtalk",
        "LSL",
        "Lua",
        "Macaulay2",
        "Makefile",
        "Mako",
        "MAQL",
        "Markdown",
        "Mask",
        "Mason",
        "Mathematica",
        "Matlab session",
        "Matlab",
        "Maxima",
        "MCFunction",
        "MCSchema",
        "Meson",
        "MIME",
        "MiniD",
        "MiniScript",
        "MIPS",
        "Modelica",
        "Modula-2",
        "MoinMoin/Trac Wiki markup",
        "Monkey",
        "Monte",
        "MOOCode",
        "MoonScript",
        "Mosel",
        "mozhashpreproc",
        "mozpercentpreproc",
        "MQL",
        "Mscgen",
        "MSDOS Session",
        "MuPAD",
        "MXML",
        "Myghty",
        "MySQL",
        "NASM",
        "NCL",
        "Nemerle",
        "nesC",
        "NestedText",
        "NewLisp",
        "Newspeak",
        "Nginx configuration file",
        "Nimrod",
        "Nix",
        "Node.js REPL console session",
        "Notmuch",
        "NSIS",
        "NuSMV",
        "objdump",
        "objdump-nasm",
        "Objective-C",
        "Objective-C++",
        "Objective-J",
        "OCaml",
        "Octave",
        "ODIN",
        "OMG Interface Definition Language",
        "Ooc",
        "Opa",
        "OpenEdge ABL",
        "PacmanConf",
        "ParaSail",
        "Pawn",
        "PEG",
        "Perl",
        "Perl6",
        "Phix",
        "PHP",
        "Pig",
        "Pike",
        "pip._vendor.pygments.lexers.actionscript",
        "pip._vendor.pygments.lexers.ada",
        "pip._vendor.pygments.lexers.algebra",
        "pip._vendor.pygments.lexers.ambient",
        "pip._vendor.pygments.lexers.amdgpu",
        "pip._vendor.pygments.lexers.ampl",
        "pip._vendor.pygments.lexers.apdlexer",
        "pip._vendor.pygments.lexers.apl",
        "pip._vendor.pygments.lexers.archetype",
        "pip._vendor.pygments.lexers.arrow",
        "pip._vendor.pygments.lexers.arturo",
        "pip._vendor.pygments.lexers.asc",
        "pip._vendor.pygments.lexers.asm",
        "pip._vendor.pygments.lexers.automation",
        "pip._vendor.pygments.lexers.bare",
        "pip._vendor.pygments.lexers.basic",
        "pip._vendor.pygments.lexers.bdd",
        "pip._vendor.pygments.lexers.berry",
        "pip._vendor.pygments.lexers.bibtex",
        "pip._vendor.pygments.lexers.business",
        "pip._vendor.pygments.lexers.c_cpp",
        "pip._vendor.pygments.lexers.c_like",
        "pip._vendor.pygments.lexers.capnproto",
        "pip._vendor.pygments.lexers.carbon",
        "pip._vendor.pygments.lexers.cddl",
        "pip._vendor.pygments.lexers.chapel",
        "pip._vendor.pygments.lexers.clean",
        "pip._vendor.pygments.lexers.comal",
        "pip._vendor.pygments.lexers.configs",
        "pip._vendor.pygments.lexers.console",
        "pip._vendor.pygments.lexers.cplint",
        "pip._vendor.pygments.lexers.crystal",
        "pip._vendor.pygments.lexers.csound",
        "pip._vendor.pygments.lexers.css",
        "pip._vendor.pygments.lexers.d",
        "pip._vendor.pygments.lexers.dalvik",
        "pip._vendor.pygments.lexers.data",
        "pip._vendor.pygments.lexers.devicetree",
        "pip._vendor.pygments.lexers.diff",
        "pip._vendor.pygments.lexers.dotnet",
        "pip._vendor.pygments.lexers.dsls",
        "pip._vendor.pygments.lexers.dylan",
        "pip._vendor.pygments.lexers.ecl",
        "pip._vendor.pygments.lexers.eiffel",
        "pip._vendor.pygments.lexers.elm",
        "pip._vendor.pygments.lexers.elpi",
        "pip._vendor.pygments.lexers.email",
        "pip._vendor.pygments.lexers.erlang",
        "pip._vendor.pygments.lexers.esoteric",
        "pip._vendor.pygments.lexers.ezhil",
        "pip._vendor.pygments.lexers.factor",
        "pip._vendor.pygments.lexers.fantom",
        "pip._vendor.pygments.lexers.felix",
        "pip._vendor.pygments.lexers.fift",
        "pip._vendor.pygments.lexers.floscript",
        "pip._vendor.pygments.lexers.forth",
        "pip._vendor.pygments.lexers.fortran",
        "pip._vendor.pygments.lexers.foxpro",
        "pip._vendor.pygments.lexers.freefem",
        "pip._vendor.pygments.lexers.func",
        "pip._vendor.pygments.lexers.futhark",
        "pip._vendor.pygments.lexers.gcodelexer",
        "pip._vendor.pygments.lexers.gdscript",
        "pip._vendor.pygments.lexers.go",
        "pip._vendor.pygments.lexers.grammar_notation",
        "pip._vendor.pygments.lexers.graph",
        "pip._vendor.pygments.lexers.graphics",
        "pip._vendor.pygments.lexers.graphviz",
        "pip._vendor.pygments.lexers.gsql",
        "pip._vendor.pygments.lexers.haskell",
        "pip._vendor.pygments.lexers.haxe",
        "pip._vendor.pygments.lexers.hdl",
        "pip._vendor.pygments.lexers.hexdump",
        "pip._vendor.pygments.lexers.html",
        "pip._vendor.pygments.lexers.idl",
        "pip._vendor.pygments.lexers.igor",
        "pip._vendor.pygments.lexers.inferno",
        "pip._vendor.pygments.lexers.installers",
        "pip._vendor.pygments.lexers.int_fiction",
        "pip._vendor.pygments.lexers.iolang",
        "pip._vendor.pygments.lexers.javascript",
        "pip._vendor.pygments.lexers.jmespath",
        "pip._vendor.pygments.lexers.jslt",
        "pip._vendor.pygments.lexers.jsonnet",
        "pip._vendor.pygments.lexers.julia",
        "pip._vendor.pygments.lexers.jvm",
        "pip._vendor.pygments.lexers.lilypond",
        "pip._vendor.pygments.lexers.lisp",
        "pip._vendor.pygments.lexers.macaulay2",
        "pip._vendor.pygments.lexers.make",
        "pip._vendor.pygments.lexers.markup",
        "pip._vendor.pygments.lexers.matlab",
        "pip._vendor.pygments.lexers.maxima",
        "pip._vendor.pygments.lexers.meson",
        "pip._vendor.pygments.lexers.mime",
        "pip._vendor.pygments.lexers.minecraft",
        "pip._vendor.pygments.lexers.mips",
        "pip._vendor.pygments.lexers.ml",
        "pip._vendor.pygments.lexers.modeling",
        "pip._vendor.pygments.lexers.modula2",
        "pip._vendor.pygments.lexers.monte",
        "pip._vendor.pygments.lexers.mosel",
        "pip._vendor.pygments.lexers.ncl",
        "pip._vendor.pygments.lexers.nimrod",
        "pip._vendor.pygments.lexers.nix",
        "pip._vendor.pygments.lexers.oberon",
        "pip._vendor.pygments.lexers.objective",
        "pip._vendor.pygments.lexers.ooc",
        "pip._vendor.pygments.lexers.parasail",
        "pip._vendor.pygments.lexers.parsers",
        "pip._vendor.pygments.lexers.pascal",
        "pip._vendor.pygments.lexers.pawn",
        "pip._vendor.pygments.lexers.perl",
        "pip._vendor.pygments.lexers.phix",
        "pip._vendor.pygments.lexers.php",
        "pip._vendor.pygments.lexers.pointless",
        "pip._vendor.pygments.lexers.pony",
        "pip._vendor.pygments.lexers.praat",
        "pip._vendor.pygments.lexers.procfile",
        "pip._vendor.pygments.lexers.prolog",
        "pip._vendor.pygments.lexers.promql",
        "pip._vendor.pygments.lexers.python",
        "pip._vendor.pygments.lexers.qlik",
        "pip._vendor.pygments.lexers.qvt",
        "pip._vendor.pygments.lexers.r",
        "pip._vendor.pygments.lexers.rdf",
        "pip._vendor.pygments.lexers.rebol",
        "pip._vendor.pygments.lexers.resource",
        "pip._vendor.pygments.lexers.ride",
        "pip._vendor.pygments.lexers.rita",
        "pip._vendor.pygments.lexers.rnc",
        "pip._vendor.pygments.lexers.roboconf",
        "pip._vendor.pygments.lexers.robotframework",
        "pip._vendor.pygments.lexers.ruby",
        "pip._vendor.pygments.lexers.rust",
        "pip._vendor.pygments.lexers.sas",
        "pip._vendor.pygments.lexers.savi",
        "pip._vendor.pygments.lexers.scdoc",
        "pip._vendor.pygments.lexers.scripting",
        "pip._vendor.pygments.lexers.sgf",
        "pip._vendor.pygments.lexers.shell",
        "pip._vendor.pygments.lexers.sieve",
        "pip._vendor.pygments.lexers.slash",
        "pip._vendor.pygments.lexers.smalltalk",
        "pip._vendor.pygments.lexers.smithy",
        "pip._vendor.pygments.lexers.smv",
        "pip._vendor.pygments.lexers.snobol",
        "pip._vendor.pygments.lexers.solidity",
        "pip._vendor.pygments.lexers.sophia",
        "pip._vendor.pygments.lexers.special",
        "pip._vendor.pygments.lexers.spice",
        "pip._vendor.pygments.lexers.sql",
        "pip._vendor.pygments.lexers.srcinfo",
        "pip._vendor.pygments.lexers.stata",
        "pip._vendor.pygments.lexers.supercollider",
        "pip._vendor.pygments.lexers.tal",
        "pip._vendor.pygments.lexers.tcl",
        "pip._vendor.pygments.lexers.teal",
        "pip._vendor.pygments.lexers.templates",
        "pip._vendor.pygments.lexers.teraterm",
        "pip._vendor.pygments.lexers.testing",
        "pip._vendor.pygments.lexers.textedit",
        "pip._vendor.pygments.lexers.textfmts",
        "pip._vendor.pygments.lexers.theorem",
        "pip._vendor.pygments.lexers.thingsdb",
        "pip._vendor.pygments.lexers.tnt",
        "pip._vendor.pygments.lexers.trafficscript",
        "pip._vendor.pygments.lexers.typoscript",
        "pip._vendor.pygments.lexers.ul4",
        "pip._vendor.pygments.lexers.unicon",
        "pip._vendor.pygments.lexers.urbi",
        "pip._vendor.pygments.lexers.usd",
        "pip._vendor.pygments.lexers.varnish",
        "pip._vendor.pygments.lexers.verification",
        "pip._vendor.pygments.lexers.webassembly",
        "pip._vendor.pygments.lexers.webidl",
        "pip._vendor.pygments.lexers.webmisc",
        "pip._vendor.pygments.lexers.wgsl",
        "pip._vendor.pygments.lexers.whiley",
        "pip._vendor.pygments.lexers.wowtoc",
        "pip._vendor.pygments.lexers.wren",
        "pip._vendor.pygments.lexers.x10",
        "pip._vendor.pygments.lexers.xorg",
        "pip._vendor.pygments.lexers.yang",
        "pip._vendor.pygments.lexers.zig",
        "PkgConfig",
        "PL/pgSQL",
        "Pointless",
        "Pony",
        "Portugol",
        "PostgreSQL console (psql)",
        "PostgreSQL EXPLAIN dialect",
        "PostgreSQL SQL dialect",
        "PostScript",
        "POVRay",
        "PowerShell Session",
        "PowerShell",
        "Praat",
        "Procfile",
        "Prolog",
        "PromQL",
        "Properties",
        "Protocol Buffer",
        "PsySH console session for PHP",
        "Pug",
        "Puppet",
        "PyPy Log",
        "Python 2.x Traceback",
        "Python 2.x",
        "Python console session",
        "Python Traceback",
        "Python",
        "Python+UL4",
        "QBasic",
        "Qlik",
        "QML",
        "QVTO",
        "Racket",
        "Ragel in C Host",
        "Ragel in CPP Host",
        "Ragel in D Host",
        "Ragel in Java Host",
        "Ragel in Objective C Host",
        "Ragel in Ruby Host",
        "Raw token data",
        "RConsole",
        "Rd",
        "ReasonML",
        "REBOL",
        "Red",
        "Redcode",
        "reg",
        "Relax-NG Compact",
        "ResourceBundle",
        "reStructuredText",
        "Rexx",
        "RHTML",
        "Ride",
        "Rita",
        "Roboconf Graph",
        "Roboconf Instances",
        "RobotFramework",
        "RPMSpec",
        "RQL",
        "RSL",
        "Ruby irb session",
        "Ruby",
        "Rust",
        "S",
        "SARL",
        "SAS",
        "Sass",
        "Savi",
        "Scala",
        "Scalate Server Page",
        "Scaml",
        "scdoc",
        "Scheme",
        "Scilab",
        "SCSS",
        "Sed",
        "Shen",
        "ShExC",
        "Sieve",
        "Silver",
        "Singularity",
        "Slash",
        "Slim",
        "Slurm",
        "Smali",
        "Smalltalk",
        "SmartGameFormat",
        "Smarty",
        "Smithy",
        "SNBT",
        "Snobol",
        "Snowball",
        "Solidity",
        "Sophia",
        "SourcePawn",
        "SPARQL",
        "Spice",
        "SQL",
        "SQL+Jinja",
        "sqlite3con",
        "SquidConf",
        "Srcinfo",
        "Stan",
        "Standard ML",
        "Stata",
        "SuperCollider",
        "Swift",
        "SWIG",
        "systemverilog",
        "TADS 3",
        "Tal",
        "TAP",
        "TASM",
        "Tcl",
        "Tcsh Session",
        "Tcsh",
        "Tea",
        "teal",
        "Tera Term macro",
        "Termcap",
        "Terminfo",
        "Terraform",
        "TeX",
        "Text only",
        "Text output",
        "ThingsDB",
        "Thrift",
        "tiddler",
        "Todotxt",
        "TOML",
        "TrafficScript",
        "Transact-SQL",
        "Treetop",
        "Turtle",
        "Twig",
        "TypeScript",
        "Typographic Number Theory",
        "TypoScript",
        "TypoScriptCssData",
        "TypoScriptHtmlData",
        "ucode",
        "Unicon",
        "Unix/Linux config files",
        "UrbiScript",
        "USD",
        "Vala",
        "VB.net",
        "VBScript",
        "VCL",
        "VCLSnippets",
        "VCTreeStatus",
        "Velocity",
        "verilog",
        "vhdl",
        "VimL",
        "WDiff",
        "Web IDL",
        "WebAssembly",
        "WebGPU Shading Language",
        "Whiley",
        "Wikitext",
        "World of Warcraft TOC",
        "Wren",
        "X++",
        "X10",
        "XML",
        "XML+Cheetah",
        "XML+Django/Jinja",
        "XML+Evoque",
        "XML+Lasso",
        "XML+Mako",
        "XML+Myghty",
        "XML+PHP",
        "XML+Ruby",
        "XML+Smarty",
        "XML+UL4",
        "XML+Velocity",
        "Xorg",
        "XQuery",
        "XSLT",
        "Xtend",
        "xtlang",
        "XUL+mozpreproc",
        "YAML",
        "YAML+Jinja",
        "YANG",
        "Zeek",
        "Zephir",
        "Zig",
        (
        ("*.[1-9]", "*.man", "*.1p", "*.3pm"),
        ("*.abap", "*.ABAP"),
        ("*.abnf",),
        ("*.adb", "*.ads", "*.ada"),
        ("*.adl", "*.adls", "*.adlf", "*.adlx"),
        ("*.aes",),
        ("*.agda",),
        ("*.aheui",),
        ("*.ahk", "*.ahkl"),
        ("*.aj",),
        ("*.alg", "*.portugol"),
        ("*.als",),
        ("*.ans",),
        ("*.apl", "*.aplf", "*.aplo", "*.apln", "*.aplc", "*.apli", "*.dyalog"),
        ("*.applescript",),
        ("*.art",),
        ("*.arw",),
        ("*.as",),
        ("*.asm", "*.ASM", "*.nasm"),
        ("*.asm", "*.ASM", "*.tasm"),
        ("*.aspx", "*.asax", "*.ascx", "*.ashx", "*.asmx", "*.axd"),
        ("*.asy",),
        ("*.at",),
        ("*.au3",),
        ("*.aug",),
        ("*.awk",),
        ("*.b",),
        ("*.bare",),
        ("*.BAS", "*.bas"),
        ("*.bas",),
        ("*.bat", "*.cmd"),
        ("*.bb", "*.decls"),
        ("*.bbc",),
        ("*.be",),
        ("*.befunge",),
        ("*.bf", "*.b"),
        ("*.bib",),
        ("*.bmx",),
        ("*.bnf",),
        ("*.boo",),
        ("*.bpl",),
        ("*.bst",),
        ("*.bug",),
        ("*.c", "*.h", "*.idc", "*.x[bp]m"),
        ("*.cadl",),
        ("*.camkes", "*.idl4"),
        ("*.capnp",),
        ("*.carbon",),
        ("*.cbl", "*.CBL"),
        ("*.cddl",),
        ("*.cdl",),
        ("*.ceylon",),
        ("*.cf",),
        ("*.cfc",),
        ("*.cfm", "*.cfml"),
        ("*.chai",),
        ("*.chpl",),
        ("*.ci",),
        ("*.cirru",),
        ("*.cl", "*.lisp"),
        ("*.clay",),
        ("*.clj", "*.cljc"),
        ("*.cljs",),
        ("*.cmake", "CMakeLists.txt"),
        ("*.cml", "*.comal"),
        ("*.cob", "*.COB", "*.cpy", "*.CPY"),
        ("*.c-objdump",),
        ("*.coffee",),
        ("*.cp", "*.cps"),
        ("*.cpp-objdump", "*.c++-objdump", "*.cxx-objdump"),
        ("*.cpsa",),
        ("*.cr",),
        ("*.crmsh", "*.pcmk"),
        ("*.croc",),
        ("*.cry",),
        ("*.cs",),
        ("*.csd",),
        ("*.css",),
        ("*.css.in",),
        ("*.css.j2", "*.css.jinja2"),
        ("*.cssul4",),
        ("*.cu", "*.cuh"),
        ("*.cw",),
        ("*.cyp", "*.cypher"),
        ("*.d", "*.di"),
        ("*.dart",),
        ("*.dasm16", "*.dasm"),
        ("*.def", "*.mod"),
        ("*.def", "Singularity"),
        ("*.dg",),
        ("*.diff", "*.patch"),
        ("*.do", "*.ado"),
        ("*.d-objdump",),
        ("*.dpatch", "*.darcspatch"),
        ("*.dtd",),
        ("*.dts", "*.dtsi"),
        ("*.duel", "*.jbst"),
        ("*.dylan", "*.dyl", "*.intr"),
        ("*.dylan-console",),
        ("*.e",),
        ("*.ebnf",),
        ("*.ec", "*.eh"),
        ("*.ecl", "*.prolog", "*.pro", "*.pl"),
        ("*.ecl", "*.prolog", "*.pro", "*.pl", "*.P", "*.lpad", "*.cpl"),
        ("*.ecl",),
        ("*.edp",),
        ("*.eg",),
        ("*.el",),
        ("*.elm",),
        ("*.elpi",),
        ("*.eml",),
        ("*.erl", "*.hrl", "*.es", "*.escript"),
        ("*.erl-sh",),
        ("*.evoque",),
        ("*.ex", "*.eex", "*.exs", "*.leex"),
        ("*.exec",),
        ("*.explain",),
        ("*.exw",),
        ("*.ezt", "*.mac"),
        ("*.f", "*.F"),
        ("*.f03", "*.f90", "*.F03", "*.F90"),
        ("*.factor",),
        ("*.fan",),
        ("*.fc", "*.func"),
        ("*.feature",),
        ("*.fif",),
        ("*.fish", "*.load"),
        ("*.flo",),
        ("*.flx", "*.flxh"),
        ("*.fnl",),
        ("*.frt", "*.fs"),
        ("*.fs", "*.fsi", "*.fsx"),
        ("*.fst", "*.fsti"),
        ("*.fut",),
        ("*.fy", "*.fancypack"),
        ("*.G", "*.g"),
        ("*.g", "*.gd", "*.gi", "*.gap"),
        ("*.gcode",),
        ("*.gd",),
        ("*.gdc",),
        ("*.go",),
        ("*.golo",),
        ("*.graph",),
        ("*.groovy", "*.gradle"),
        ("*.gs", "*.gsx", "*.gsp", "*.vark"),
        ("*.gsql",),
        ("*.gst",),
        ("*.gv", "*.dot"),
        ("*.haml",),
        ("*.handlebars", "*.hbs"),
        ("*.hlsl", "*.hlsli"),
        ("*.hs",),
        ("*.hsail",),
        ("*.html", "*.htm", "*.xhtml", "*.xslt"),
        ("*.html",),
        ("*.htmlul4",),
        ("*.hx", "*.hxsl"),
        ("*.hxml",),
        ("*.hy", "*.hyb"),
        ("*.hy",),
        ("*.i6t",),
        ("*.icl", "*.dcl"),
        ("*.icn",),
        ("*.icon", "*.ICON"),
        ("*.idl", "*.pidl"),
        ("*.idr",),
        ("*.ik",),
        ("*.inf",),
        ("*.ino",),
        ("*.instances",),
        ("*.io",),
        ("*.ipf",),
        ("*.isa",),
        ("*.j",),
        ("*.jag", "*.bug"),
        ("*.java",),
        ("*.jcl",),
        ("*.jl",),
        ("*.jp",),
        ("*.js", "*.jsm", "*.mjs", "*.cjs"),
        ("*.js.in",),
        ("*.js.j2", "*.js.jinja2"),
        ("*.jsgf",),
        ("*.jslt",),
        ("*.json", "Pipfile.lock"),
        ("*.jsonld",),
        ("*.jsonnet", "*.libsonnet"),
        ("*.jsp",),
        ("*.jsul4",),
        ("*.juttle",),
        ("*.kal",),
        ("*.kid",),
        ("*.kk", "*.kki"),
        ("*.kmsg", "*.dmesg"),
        ("*.kt", "*.kts"),
        ("*.lagda",),
        ("*.lasso", "*.lasso[89]"),
        ("*.lcry",),
        ("*.lean",),
        ("*.less",),
        ("*.lgt", "*.logtalk"),
        ("*.lhs",),
        ("*.lid", "*.hdp"),
        ("*.lidr",),
        ("*.liquid",),
        ("*.ll",),
        ("*.ls",),
        ("*.lsl",),
        ("*.lsp", "*.nl", "*.kif"),
        ("*.lua", "*.wlua"),
        ("*.ly",),
        ("*.m", "*.h"),
        ("*.m", "*.mhtml", "*.mc", "*.mi", "autohandler", "dhandler"),
        ("*.m",),
        ("*.m2",),
        ("*.mac", "*.max"),
        ("*.mak", "*.mk", "Makefile", "makefile", "Makefile.*", "GNUmakefile"),
        ("*.mao",),
        ("*.maql",),
        ("*.mask",),
        ("*.mcfunction",),
        ("*.mcschema",),
        ("*.md", "*.markdown"),
        ("*.mips", "*.MIPS"),
        ("*.mir",),
        ("*.ml", "*.mli", "*.mll", "*.mly"),
        ("*.mm", "*.hh"),
        ("*.mo",),
        ("*.monkey",),
        ("*.moo",),
        ("*.moon",),
        ("*.mos",),
        ("*.mq4", "*.mq5", "*.mqh"),
        ("*.ms",),
        ("*.msc",),
        ("*.mt",),
        ("*.mu",),
        ("*.mxml",),
        ("*.myt", "autodelegate"),
        ("*.n",),
        ("*.nb", "*.cdf", "*.nbp", "*.ma"),
        ("*.nc",),
        ("*.ncl",),
        ("*.ng2",),
        ("*.ni", "*.i7x"),
        ("*.nim", "*.nimrod"),
        ("*.nix",),
        ("*.ns2",),
        ("*.nsi", "*.nsh"),
        ("*.nt",),
        ("*.objdump",),
        ("*.objdump-intel",),
        ("*.odin",),
        ("*.ooc",),
        ("*.opa",),
        ("*.orc", "*.udo"),
        ("*.p", "*.cls"),
        ("*.p", "*.pwn", "*.inc"),
        ("*.pas", "*.dpr"),
        ("*.pc",),
        ("*.peg",),
        ("*.php", "*.php[345]", "*.inc"),
        ("*.phtml",),
        ("*.pig",),
        ("*.pike", "*.pmod"),
        ("*.pl", "*.pm", "*.t", "*.perl"),
        ("*.plot", "*.plt"),
        ("*.pony",),
        ("*.pot", "*.po"),
        ("*.pov", "*.inc"),
        ("*.pp",),
        ("*.praat", "*.proc", "*.psc"),
        ("*.PRG", "*.prg"),
        ("*.pro",),
        ("*.promql",),
        ("*.properties",),
        ("*.proto",),
        ("*.ps", "*.eps"),
        ("*.ps1", "*.psm1"),
        ("*.psi", "*.psl"),
        ("*.ptls",),
        ("*.pug", "*.jade"),
        ("*.py2tb",),
        ("*.pypylog",),
        ("*.pytb", "*.py3tb"),
        ("*.pyul4",),
        ("*.pyx", "*.pxd", "*.pxi"),
        ("*.qml", "*.qbs"),
        ("*.qvs", "*.qvw"),
        ("*.qvto",),
        ("*.r", "*.r3", "*.reb"),
        ("*.Rd",),
        ("*.re", "*.rei"),
        ("*.red", "*.reds"),
        ("*.reg",),
        ("*.rexx", "*.rex", "*.rx", "*.arexx"),
        ("*.rhtml",),
        ("*.ride",),
        ("*.rita",),
        ("*.rkt", "*.rktd", "*.rktl"),
        ("*.rl",),
        ("*.rnc",),
        ("*.robot", "*.resource"),
        ("*.Rout",),
        ("*.rq", "*.sparql"),
        ("*.rql",),
        ("*.rs", "*.rs.in"),
        ("*.rsl",),
        ("*.rst", "*.rest"),
        ("*.rts",),
        ("*.run",),
        ("*.S", "*.R", ".Rhistory", ".Rprofile", ".Renviron"),
        ("*.s", "*.S"),
        ("*.s",),
        ("*.sarl",),
        ("*.SAS", "*.sas"),
        ("*.sass",),
        ("*.savi",),
        ("*.sbl",),
        ("*.sc", "*.scd"),
        ("*.scala",),
        ("*.scaml",),
        ("*.scd", "*.scdoc"),
        ("*.sci", "*.sce", "*.tst"),
        ("*.scm", "*.ss"),
        ("*.sco",),
        ("*.scss",),
        ("*.sed", "*.[gs]sed"),
        ("*.sgf",),
        ("*.shen",),
        ("*.shex",),
        ("*.sh-session", "*.shell-session"),
        ("*.sil", "*.vpr"),
        ("*.siv", "*.sieve"),
        ("*.sl",),
        ("*.sla",),
        ("*.slim",),
        ("*.sls", "*.yaml.j2", "*.yml.j2", "*.yaml.jinja2", "*.yml.jinja2"),
        ("*.smali",),
        ("*.smithy",),
        ("*.sml", "*.sig", "*.fun"),
        ("*.smv",),
        ("*.snbt",),
        ("*.snobol",),
        ("*.sol",),
        ("*.sp",),
        ("*.spec",),
        ("*.spice",),
        ("*.sql", "*.sql.j2", "*.sql.jinja2"),
        ("*.sql",),
        ("*.sqlite3-console",),
        ("*.ssp",),
        ("*.st",),
        ("*.stan",),
        ("*.sv", "*.svh"),
        ("*.swg", "*.i"),
        ("*.swift",),
        ("*.t",),
        ("*.tal",),
        ("*.tap",),
        ("*.tcl", "*.rvt"),
        ("*.tcsh", "*.csh"),
        ("*.tea",),
        ("*.teal",),
        ("*.tex", "*.aux", "*.toc"),
        ("*.tf", "*.hcl"),
        ("*.thrift",),
        ("*.thy",),
        ("*.ti",),
        ("*.tid",),
        ("*.tmpl", "*.spt"),
        ("*.tnt",),
        ("*.toc",),
        ("*.toml", "Pipfile", "poetry.lock"),
        ("*.tpl",),
        ("*.treetop", "*.tt"),
        ("*.ts",),
        ("*.tst",),
        ("*.ttl",),
        ("*.twig",),
        ("*.txt",),
        ("*.typoscript",),
        ("*.u", "*.u1", "*.u2"),
        ("*.u",),
        ("*.usd", "*.usda"),
        ("*.v",),
        ("*.vala", "*.vapi"),
        ("*.vb", "*.bas"),
        ("*.vbs", "*.VBS"),
        ("*.vcl",),
        ("*.vert", "*.frag", "*.geo"),
        ("*.vhdl", "*.vhd"),
        ("*.vm", "*.fhtml"),
        ("*.wat", "*.wast"),
        ("*.wdiff",),
        ("*.webidl",),
        ("*.weechatlog",),
        ("*.wgsl",),
        ("*.whiley",),
        ("*.wren",),
        ("*.x", "*.xi", "*.xm", "*.xmi"),
        ("*.x10",),
        ("*.xml", "*.xsl", "*.rss", "*.xslt", "*.xsd", "*.wsdl", "*.wsf"),
        ("*.xml",),
        ("*.xml.j2", "*.xml.jinja2"),
        ("*.xmlul4",),
        ("*.xpp",),
        ("*.xqy", "*.xquery", "*.xq", "*.xql", "*.xqm"),
        ("*.xsl", "*.xslt", "*.xpl"),
        ("*.xtend",),
        ("*.xtm",),
        ("*.xul.in",),
        ("*.yaml", "*.yml"),
        ("*.yang",),
        ("*.zeek", "*.bro"),
        ("*.zep",),
        ("*.zig",),
        ("*Spec.hs",),
        (".htaccess", "apache.conf", "apache2.conf"),
        (".SRCINFO",),
        ("abap",),
        ("abnf",),
        ("actionscript", "as"),
        ("actionscript3", "as3"),
        ("ada", "ada95", "ada2005"),
        ("adl",),
        ("agda",),
        ("aheui",),
        ("alloy",),
        ("ambienttalk", "ambienttalk/2", "at"),
        ("amdgpu",),
        ("ampl",),
        ("ansys", "apdl"),
        ("antlr-actionscript", "antlr-as"),
        ("antlr-cpp",),
        ("antlr-csharp", "antlr-c#"),
        ("antlr-java",),
        ("antlr-objc",),
        ("antlr-perl",),
        ("antlr-python",),
        ("antlr-ruby", "antlr-rb"),
        ("apacheconf", "aconf", "apache"),
        ("apl",),
        ("applescript",),
        ("application/jsgf", "application/x-jsgf", "text/jsgf"),
        ("application/json", "application/json-object"),
        ("application/juttle", "application/x-juttle", "text/x-juttle", "text/juttle"),
        ("application/ld+json",),
        ("application/postscript",),
        ("application/sparql-query",),
        ("application/supercollider", "text/supercollider"),
        ("application/x-actionscript", "text/x-actionscript", "text/actionscript"),
        ("application/x-actionscript3", "text/x-actionscript3", "text/actionscript3"),
        ("application/x-awk",),
        ("application/x-befunge",),
        ("application/x-brainfuck",),
        ("application/x-cheetah", "application/x-spitfire"),
        ("application/x-coldfusion",),
        ("application/x-csh",),
        ("application/x-django-templating", "application/x-jinja"),
        ("application/x-dos-batch",),
        ("application/x-ecl",),
        ("application/x-evoque",),
        ("application/x-fantom",),
        ("application/x-fish",),
        ("application/x-forth",),
        ("application/x-genshi", "application/x-kid"),
        ("application/x-genshi-text", "text/x-genshi"),
        ("application/x-gettext", "text/x-gettext", "text/gettext"),
        ("application/x-jsp",),
        ("application/x-mako",),
        ("application/x-mason",),
        ("application/xml+cheetah", "application/xml+spitfire"),
        ("application/xml+django", "application/xml+jinja"),
        ("application/xml+evoque",),
        ("application/xml+lasso",),
        ("application/xml+mako",),
        ("application/xml+myghty",),
        ("application/xml+php",),
        ("application/xml+ruby",),
        ("application/xml+smarty",),
        ("application/xml+velocity",),
        ("application/xml-dtd",),
        ("application/x-myghty",),
        ("application/x-pygments-tokens",),
        ("application/x-pypylog",),
        ("application/x-qml", "application/x-qt.qbs+qml"),
        ("application/x-ruby-templating",),
        ("application/x-sh", "application/x-shellscript", "text/x-shellscript"),
        ("application/x-shell-session", "application/x-sh-session"),
        ("application/xsl+xml", "application/xslt+xml"),
        ("application/x-smarty",),
        ("application/x-ssp",),
        ("application/x-tf", "application/x-terraform"),
        ("application/x-thrift",),
        ("application/x-troff", "text/troff"),
        ("application/x-twig",),
        ("application/x-typescript", "text/x-typescript"),
        ("application/x-urbiscript",),
        ("application/yang",),
        ("arduino",),
        ("arrow",),
        ("arturo", "art"),
        ("asc", "pem"),
        ("aspectj",),
        ("aspx-cs",),
        ("aspx-vb",),
        ("asymptote", "asy"),
        ("augeas",),
        ("autohotkey", "ahk"),
        ("autoit",),
        ("awk", "gawk", "mawk", "nawk"),
        ("bare",),
        ("basemake",),
        ("bash", "sh", "ksh", "zsh", "shell"),
        ("batch", "bat", "dosbatch", "winbatch"),
        ("bbcbasic",),
        ("bbcode",),
        ("bdd",),
        ("befunge",),
        ("berry", "be"),
        ("bibtex", "bib"),
        ("blitzbasic", "b3d", "bplus"),
        ("blitzmax", "bmax"),
        ("bnf",),
        ("boo",),
        ("boogie",),
        ("brainfuck", "bf"),
        ("bst", "bst-pybtex"),
        ("bugs", "winbugs", "openbugs"),
        ("c",),
        ("ca65",),
        ("cadl",),
        ("camkes", "idl4"),
        ("capdl",),
        ("capnp",),
        ("carbon",),
        ("cbmbas",),
        ("cddl",),
        ("ceylon",),
        ("cfc",),
        ("cfengine3", "cf3"),
        ("cfm",),
        ("cfs",),
        ("chaiscript", "chai"),
        ("chapel", "chpl"),
        ("charmci",),
        ("cheetah", "spitfire"),
        ("cirru",),
        ("clay",),
        ("clean",),
        ("clojure", "clj"),
        ("clojurescript", "cljs"),
        ("cmake",),
        ("c-objdump",),
        ("cobol",),
        ("cobolfree",),
        ("coffeescript", "coffee-script", "coffee"),
        ("comal", "comal80"),
        ("common-lisp", "cl", "lisp"),
        ("componentpascal", "cp"),
        ("console", "shell-session"),
        ("control",),
        ("coq",),
        ("cplint",),
        ("cpp", "c++"),
        ("cpp-objdump", "c++-objdumb", "cxx-objdump"),
        ("cpsa",),
        ("cr", "crystal"),
        ("crmsh", "pcmk"),
        ("croc",),
        ("cryptol", "cry"),
        ("csharp", "c#", "cs"),
        ("csound", "csound-orc"),
        ("csound-document", "csound-csd"),
        ("csound-score", "csound-sco"),
        ("css",),
        ("css+django", "css+jinja"),
        ("css+genshitext", "css+genshi"),
        ("css+lasso",),
        ("css+mako",),
        ("css+mozpreproc",),
        ("css+myghty",),
        ("css+php",),
        ("css+ruby", "css+erb"),
        ("css+smarty",),
        ("css+ul4",),
        ("cuda", "cu"),
        ("cypher",),
        ("cython", "pyx", "pyrex"),
        ("d",),
        ("dart",),
        ("dasm16",),
        ("debcontrol", "control"),
        ("debsources", "sourceslist", "sources.list"),
        ("delphi", "pas", "pascal", "objectpascal"),
        ("devicetree", "dts"),
        ("dg",),
        ("diff", "udiff"),
        ("django", "jinja"),
        ("d-objdump",),
        ("docker", "dockerfile"),
        ("Dockerfile", "*.docker"),
        ("doscon",),
        ("dpatch",),
        ("dtd",),
        ("duel", "jbst", "jsonml+bst"),
        ("dylan",),
        ("dylan-console", "dylan-repl"),
        ("dylan-lid", "lid"),
        ("earl-grey", "earlgrey", "eg"),
        ("easytrieve",),
        ("ebnf",),
        ("ec",),
        ("ecl",),
        ("eiffel",),
        ("elixir", "ex", "exs"),
        ("elm",),
        ("elpi",),
        ("emacs-lisp", "elisp", "emacs"),
        ("email", "eml"),
        ("erb",),
        ("erl",),
        ("erlang",),
        ("evoque",),
        ("execline",),
        ("extempore",),
        ("ezhil",),
        ("factor",),
        ("fan",),
        ("fancy", "fy"),
        ("felix", "flx"),
        ("fennel", "fnl"),
        ("fift", "fif"),
        ("fish", "fishshell"),
        ("flatline",),
        ("floscript", "flo"),
        ("forth",),
        ("fortran", "f90"),
        ("fortranfixed",),
        ("foxpro", "vfp", "clipper", "xbase"),
        ("freefem",),
        ("fsharp", "f#"),
        ("fstar",),
        ("func", "fc"),
        ("futhark",),
        ("gap",),
        ("gap-console", "gap-repl"),
        ("gas", "asm"),
        ("gcode",),
        ("gdscript", "gd"),
        ("genshi", "kid", "xml+genshi", "xml+kid"),
        ("genshitext",),
        ("gherkin", "cucumber"),
        ("glsl",),
        ("gnuplot",),
        ("go", "golang"),
        ("golo",),
        ("gooddata-cl",),
        ("gosu",),
        ("graphviz", "dot"),
        ("groff", "nroff", "man"),
        ("groovy",),
        ("gsql",),
        ("gst",),
        ("haml",),
        ("handlebars",),
        ("haskell", "hs"),
        ("haxe", "hxsl", "hx"),
        ("haxeml", "hxml"),
        ("hexdump",),
        ("hlsl",),
        ("hsail", "hsa"),
        ("hspec",),
        ("html",),
        ("html+cheetah", "html+spitfire", "htmlcheetah"),
        ("html+django", "html+jinja", "htmldjango"),
        ("html+evoque",),
        ("html+genshi", "html+kid"),
        ("html+handlebars",),
        ("html+lasso",),
        ("html+mako",),
        ("html+myghty",),
        ("html+ng2",),
        ("html+php",),
        ("html+smarty",),
        ("html+twig",),
        ("html+ul4",),
        ("html+velocity",),
        ("hybris", "hy"),
        ("hylang",),
        ("i6t",),
        ("icon",),
        ("idl",),
        ("idris", "idr"),
        ("iex",),
        ("igor", "igorpro"),
        ("inform6", "i6"),
        ("inform7", "i7"),
        ("ini", "cfg", "dosini"),
        ("io",),
        ("ioke", "ik"),
        ("irc",),
        ("isabelle",),
        ("jags",),
        ("jasmin", "jasminxt"),
        ("java",),
        ("javascript", "js"),
        ("javascript+cheetah", "js+cheetah", "javascript+spitfire", "js+spitfire"),
        ("javascript+django", "js+django", "javascript+jinja", "js+jinja"),
        ("javascript+lasso", "js+lasso"),
        ("javascript+mako", "js+mako"),
        ("javascript+mozpreproc",),
        ("javascript+myghty", "js+myghty"),
        ("javascript+php", "js+php"),
        ("javascript+ruby", "js+ruby", "javascript+erb", "js+erb"),
        ("javascript+smarty", "js+smarty"),
        ("jcl",),
        ("jlcon", "julia-repl"),
        ("jmespath", "jp"),
        ("js+genshitext", "js+genshi", "javascript+genshitext", "javascript+genshi"),
        ("js+ul4",),
        ("jsgf",),
        ("jslt",),
        ("json", "json-object"),
        ("jsonld", "json-ld"),
        ("jsonnet",),
        ("jsp",),
        ("julia", "jl"),
        ("juttle",),
        ("kal",),
        ("kconfig", "menuconfig", "linux-config", "kernel-config"),
        ("Kconfig*", "*Config.in*", "external.in*", "standard-modules.in"),
        ("kmsg", "dmesg"),
        ("koka",),
        ("kotlin",),
        ("lasso", "lassoscript"),
        ("lean",),
        ("less",),
        ("lighttpd", "lighty"),
        ("lighttpd.conf",),
        ("lilypond",),
        ("limbo",),
        ("liquid",),
        ("literate-agda", "lagda"),
        ("literate-cryptol", "lcryptol", "lcry"),
        ("literate-haskell", "lhaskell", "lhs"),
        ("literate-idris", "lidris", "lidr"),
        ("livescript", "live-script"),
        ("llvm",),
        ("llvm-mir",),
        ("llvm-mir-body",),
        ("logos",),
        ("logtalk",),
        ("lsl",),
        ("lua",),
        ("macaulay2",),
        ("make", "makefile", "mf", "bsdmake"),
        ("mako",),
        ("maql",),
        ("markdown", "md"),
        ("mask",),
        ("mason",),
        ("mathematica", "mma", "nb"),
        ("matlab",),
        ("matlabsession",),
        ("maxima", "macsyma"),
        ("mcfunction", "mcf"),
        ("mcschema",),
        ("meson", "meson.build"),
        ("meson.build", "meson_options.txt"),
        ("message/rfc822",),
        ("mime",),
        ("minid",),
        ("miniscript", "ms"),
        ("mips",),
        ("modelica",),
        ("modula2", "m2"),
        ("monkey",),
        ("monte",),
        ("moocode", "moo"),
        ("moonscript", "moon"),
        ("mosel",),
        ("mozhashpreproc",),
        ("mozpercentpreproc",),
        ("mql", "mq4", "mq5", "mql4", "mql5"),
        ("mscgen", "msc"),
        ("multipart/mixed", "multipart/related", "multipart/alternative"),
        ("mupad",),
        ("mxml",),
        ("myghty",),
        ("mysql",),
        ("nasm",),
        ("ncl",),
        ("nemerle",),
        ("nesc",),
        ("nestedtext", "nt"),
        ("newlisp",),
        ("newspeak",),
        ("ng2",),
        ("nginx",),
        ("nginx.conf",),
        ("nimrod", "nim"),
        ("nixos", "nix"),
        ("nodejsrepl",),
        ("notmuch",),
        ("nsis", "nsi", "nsh"),
        ("nusmv",),
        ("objdump",),
        ("objdump-nasm",),
        ("objective-c", "objectivec", "obj-c", "objc"),
        ("objective-c++", "objectivec++", "obj-c++", "objc++"),
        ("objective-j", "objectivej", "obj-j", "objj"),
        ("ocaml",),
        ("octave",),
        ("odin",),
        ("omg-idl",),
        ("ooc",),
        ("opa",),
        ("openedge", "abl", "progress"),
        ("output",),
        ("pacman.conf",),
        ("pacmanconf",),
        ("parasail",),
        ("pawn",),
        ("peg",),
        ("perl", "pl"),
        ("perl6", "pl6", "raku"),
        ("phix",),
        ("php", "php3", "php4", "php5"),
        ("pig",),
        ("pike",),
        ("pkgconfig",),
        ("plpgsql",),
        ("pointless",),
        ("pony",),
        ("portugol",),
        ("postgres-explain",),
        ("postgresql", "postgres"),
        ("postscript", "postscr"),
        ("pot", "po"),
        ("pov",),
        ("powershell", "pwsh", "posh", "ps1", "psm1"),
        ("praat",),
        ("procfile",),
        ("Procfile",),
        ("prolog",),
        ("promql",),
        ("properties", "jproperties"),
        ("protobuf", "proto"),
        ("psql", "postgresql-console", "postgres-console"),
        ("psysh",),
        ("pug", "jade"),
        ("puppet",),
        ("pwsh-session", "ps1con"),
        ("py+ul4",),
        ("py2tb",),
        ("pycon",),
        ("pypylog", "pypy"),
        ("pytb", "py3tb"),
        ("python", "py", "sage", "python3", "py3"),
        ("python2", "py2"),
        ("qbasic", "basic"),
        ("qlik", "qlikview", "qliksense", "qlikscript"),
        ("qml", "qbs"),
        ("qvto", "qvt"),
        ("racket", "rkt"),
        ("ragel-c",),
        ("ragel-cpp",),
        ("ragel-d",),
        ("ragel-em",),
        ("ragel-java",),
        ("ragel-objc",),
        ("ragel-ruby", "ragel-rb"),
        ("rbcon", "irb"),
        ("rconsole", "rout"),
        ("rd",),
        ("reasonml", "reason"),
        ("rebol",),
        ("red", "red/system"),
        ("redcode",),
        ("registry",),
        ("resourcebundle", "resource"),
        ("restructuredtext", "rst", "rest"),
        ("rexx", "arexx"),
        ("rhtml", "html+erb", "html+ruby"),
        ("ride",),
        ("rita",),
        ("rng-compact", "rnc"),
        ("roboconf-graph",),
        ("roboconf-instances",),
        ("robotframework",),
        ("rql",),
        ("rsl",),
        ("ruby", "rb", "duby"),
        ("rust", "rs"),
        ("sarl",),
        ("sas",),
        ("sass",),
        ("savi",),
        ("scala",),
        ("scaml",),
        ("scdoc", "scd"),
        ("scheme", "scm"),
        ("scilab",),
        ("scss",),
        ("sed", "gsed", "ssed"),
        ("sgf",),
        ("shen",),
        ("shexc", "shex"),
        ("sieve",),
        ("silver",),
        ("singularity",),
        ("slash",),
        ("slim",),
        ("slurm", "sbatch"),
        ("smali",),
        ("smalltalk", "squeak", "st"),
        ("smarty",),
        ("smithy",),
        ("sml",),
        ("snbt",),
        ("snobol",),
        ("snowball",),
        ("solidity",),
        ("sophia",),
        ("sources.list",),
        ("sp",),
        ("sparql",),
        ("spec",),
        ("spice", "spicelang"),
        ("splus", "s", "r"),
        ("sql",),
        ("sql+jinja",),
        ("sqlite3",),
        ("squid.conf",),
        ("squidconf", "squid.conf", "squid"),
        ("srcinfo",),
        ("ssp",),
        ("stan",),
        ("stata", "do"),
        ("supercollider", "sc"),
        ("swift",),
        ("swig",),
        ("systemverilog", "sv"),
        ("tads3",),
        ("tal", "uxntal"),
        ("tap",),
        ("tasm",),
        ("tcl",),
        ("tcsh", "csh"),
        ("tcshcon",),
        ("tea",),
        ("teal",),
        ("teratermmacro", "teraterm", "ttl"),
        ("termcap", "termcap.src"),
        ("termcap",),
        ("terminfo", "terminfo.src"),
        ("terminfo",),
        ("terraform", "tf", "hcl"),
        ("tex", "latex"),
        ("text",),
        ("text/basic",),
        ("text/coffeescript",),
        ("text/css",),
        ("text/css+django", "text/css+jinja"),
        ("text/css+genshi",),
        ("text/css+lasso",),
        ("text/css+mako",),
        ("text/css+myghty",),
        ("text/css+php",),
        ("text/css+ruby",),
        ("text/css+smarty",),
        ("text/haxe", "text/x-haxe", "text/x-hx"),
        ("text/html", "application/xhtml+xml"),
        ("text/html+cheetah", "text/html+spitfire"),
        ("text/html+django", "text/html+jinja"),
        ("text/html+evoque",),
        ("text/html+genshi",),
        ("text/html+handlebars", "text/x-handlebars-template"),
        ("text/html+mako",),
        ("text/html+myghty",),
        ("text/html+ruby",),
        ("text/html+smarty",),
        ("text/html+twig",),
        ("text/html+velocity",),
        ("text/idl",),
        ("text/ipf",),
        ("text/kal", "application/kal"),
        ("text/limbo",),
        ("text/livescript",),
        ("text/matlab",),
        ("text/mcfunction",),
        ("text/mcschema",),
        ("text/ncl",),
        ("text/octave",),
        ("text/odin",),
        ("text/plain",),
        ("text/rita",),
        ("text/rsl",),
        ("text/rust", "text/x-rust"),
        ("text/scilab",),
        ("text/shex",),
        ("text/smali",),
        ("text/snbt",),
        ("text/swig",),
        ("text/turtle", "application/x-turtle"),
        ("text/unicon",),
        ("text/vnd.tiddlywiki",),
        ("text/wgsl",),
        ("text/x-abap",),
        ("text/x-abnf",),
        ("text/x-ada",),
        ("text/x-agda",),
        ("text/x-alloy",),
        ("text/x-ambienttalk",),
        ("text/x-apacheconf",),
        ("text/x-arduino",),
        ("text/x-aspectj",),
        ("text/x-asymptote",),
        ("text/x-autohotkey",),
        ("text/x-autoit",),
        ("text/x-bb",),
        ("text/x-bbcode",),
        ("text/x-bdd",),
        ("text/x-berry", "application/x-berry"),
        ("text/x-bibtex",),
        ("text/x-bmx",),
        ("text/x-bnf",),
        ("text/x-boo",),
        ("text/x-c",),
        ("text/x-c++hdr", "text/x-c++src"),
        ("text/x-carbon",),
        ("text/x-cddl",),
        ("text/x-ceylon",),
        ("text/x-chaiscript", "application/x-chaiscript"),
        ("text/x-chdr", "text/x-csrc", "image/x-xbitmap", "image/x-xpixmap"),
        ("text/x-cirru",),
        ("text/x-clay",),
        ("text/x-clojure", "application/x-clojure"),
        ("text/x-clojurescript", "application/x-clojurescript"),
        ("text/x-cmake",),
        ("text/x-c-objdump",),
        ("text/x-cobol",),
        ("text/x-common-lisp",),
        ("text/x-component-pascal",),
        ("text/x-coq",),
        ("text/x-cplint",),
        ("text/x-cpp-objdump",),
        ("text/x-crocsrc",),
        ("text/x-cryptol",),
        ("text/x-crystal",),
        ("text/x-csharp",),
        ("text/x-cuda",),
        ("text/x-cython", "application/x-cython"),
        ("text/x-dart",),
        ("text/x-dasm16",),
        ("text/x-dg",),
        ("text/x-diff", "text/x-patch"),
        ("text/x-d-objdump",),
        ("text/x-dockerfile-config",),
        ("text/x-dsrc",),
        ("text/x-duel", "text/x-jbst"),
        ("text/x-dylan",),
        ("text/x-dylan-console",),
        ("text/x-dylan-lid",),
        ("text/x-earl-grey",),
        ("text/x-easytrieve",),
        ("text/x-ebnf",),
        ("text/x-echdr", "text/x-ecsrc"),
        ("text/x-eiffel",),
        ("text/x-elisp", "application/x-elisp"),
        ("text/x-elixir",),
        ("text/x-elixir-shellsession",),
        ("text/x-elm",),
        ("text/x-elpi",),
        ("text/x-erlang",),
        ("text/x-erl-shellsession",),
        ("text/x-ezhil",),
        ("text/x-factor",),
        ("text/x-fancysrc",),
        ("text/x-felix",),
        ("text/x-flatline",),
        ("text/x-fortran",),
        ("text/x-freefem",),
        ("text/x-fsharp",),
        ("text/x-fstar",),
        ("text/x-futhark",),
        ("text/x-gas",),
        ("text/x-gdscript", "application/x-gdscript"),
        ("text/x-gherkin",),
        ("text/x-glslsrc",),
        ("text/x-gnuplot",),
        ("text/x-gooddata-cl",),
        ("text/x-gooddata-maql", "application/x-gooddata-maql"),
        ("text/x-gosrc",),
        ("text/x-gosu",),
        ("text/x-gosu-template",),
        ("text/x-graphviz", "text/vnd.graphviz"),
        ("text/x-groovy",),
        ("text/x-haml",),
        ("text/x-haskell",),
        ("text/x-hlsl",),
        ("text/x-hsail",),
        ("text/x-hy", "application/x-hy"),
        ("text/x-hybris", "application/x-hybris"),
        ("text/x-idris",),
        ("text/x-ini", "text/inf"),
        ("text/x-iokesrc",),
        ("text/x-iosrc",),
        ("text/x-irclog",),
        ("text/x-isabelle",),
        ("text/x-java",),
        ("text/x-java-properties",),
        ("text/x-jcl",),
        ("text/x-jslt",),
        ("text/x-julia", "application/x-julia"),
        ("text/x-kconfig",),
        ("text/x-koka",),
        ("text/x-kotlin",),
        ("text/x-lasso",),
        ("text/x-lean",),
        ("text/x-less-css",),
        ("text/x-lighttpd-conf",),
        ("text/x-literate-agda",),
        ("text/x-literate-cryptol",),
        ("text/x-literate-haskell",),
        ("text/x-literate-idris",),
        ("text/x-llvm",),
        ("text/x-logos",),
        ("text/x-logtalk",),
        ("text/x-lsl",),
        ("text/x-lua", "application/x-lua"),
        ("text/x-makefile",),
        ("text/x-markdown",),
        ("text/x-mask",),
        ("text/x-meson",),
        ("text/x-minicript", "application/x-miniscript"),
        ("text/x-minidsrc",),
        ("text/x-modelica",),
        ("text/x-modula2",),
        ("text/x-monkey",),
        ("text/x-moocode",),
        ("text/x-moonscript", "application/x-moonscript"),
        ("text/x-mql",),
        ("text/x-mysql",),
        ("text/x-nasm",),
        ("text/x-nasm-objdump",),
        ("text/x-nemerle",),
        ("text/x-nescsrc",),
        ("text/x-newlisp", "application/x-newlisp"),
        ("text/x-newspeak",),
        ("text/x-nginx-conf",),
        ("text/x-nim",),
        ("text/x-nix",),
        ("text/x-nodejsrepl",),
        ("text/x-nsis",),
        ("text/x-objdump",),
        ("text/x-objective-c",),
        ("text/x-objective-c++",),
        ("text/x-objective-j",),
        ("text/x-ocaml",),
        ("text/x-ooc",),
        ("text/x-opa",),
        ("text/x-openedge", "application/x-openedge"),
        ("text/x-parasail",),
        ("text/x-pascal",),
        ("text/x-pawn",),
        ("text/x-peg",),
        ("text/x-perl", "application/x-perl"),
        ("text/x-perl6", "application/x-perl6"),
        ("text/x-phix",),
        ("text/x-php",),
        ("text/x-pig",),
        ("text/x-pike",),
        ("text/x-plpgsql",),
        ("text/x-postgresql",),
        ("text/x-postgresql-explain",),
        ("text/x-postgresql-psql",),
        ("text/x-povray",),
        ("text/x-powershell",),
        ("text/x-prolog",),
        ("text/x-pug", "text/x-jade"),
        ("text/x-python2", "application/x-python2"),
        ("text/x-python2-traceback",),
        ("text/x-python-doctest",),
        ("text/x-python-traceback", "text/x-python3-traceback"),
        ("text/xquery", "application/xquery"),
        ("text/x-racket", "application/x-racket"),
        ("text/x-r-doc",),
        ("text/x-reasonml",),
        ("text/x-rebol",),
        ("text/x-red", "text/x-red-system"),
        ("text/x-rexx",),
        ("text/x-ride",),
        ("text/x-robotframework",),
        ("text/x-rpm-spec",),
        ("text/x-rql",),
        ("text/x-rst", "text/prs.fallenstein.rst"),
        ("text/x-ruby", "application/x-ruby"),
        ("text/x-ruby-shellsession",),
        ("text/x-sarl",),
        ("text/x-sas", "text/sas", "application/x-sas"),
        ("text/x-sass",),
        ("text/x-scala",),
        ("text/x-scaml",),
        ("text/x-scheme", "application/x-scheme"),
        ("text/x-scss",),
        ("text/x-sed",),
        ("text/x-shen", "application/x-shen"),
        ("text/x-slim",),
        ("text/x-smalltalk",),
        ("text/x-snobol",),
        ("text/x-sourcepawn",),
        ("text/x-spice",),
        ("text/x-sql",),
        ("text/x-sqlite3-console",),
        ("text/x-squidconf",),
        ("text/x-standardml", "application/x-standardml"),
        ("text/x-stata", "text/stata", "application/x-stata"),
        ("text/x-swift",),
        ("text/x-systemverilog",),
        ("text/x-tasm",),
        ("text/x-tcl", "text/x-script.tcl", "application/x-tcl"),
        ("text/x-tea",),
        ("text/x-teratermmacro",),
        ("text/x-tex", "text/x-latex"),
        ("text/x-todo",),
        ("text/x-trac-wiki",),
        ("text/x-tsql",),
        ("text/x-typoscript",),
        ("text/x-uxntal",),
        ("text/x-vala",),
        ("text/x-vbnet", "text/x-vba"),
        ("text/x-vclsnippet",),
        ("text/x-vclsrc",),
        ("text/x-verilog",),
        ("text/x-vhdl",),
        ("text/x-vim",),
        ("text/x-whiley",),
        ("text/x-wiki",),
        ("text/x-windows-registry",),
        ("text/x-x10",),
        ("text/x-xtend",),
        ("text/x-yaml",),
        ("text/x-yaml+jinja", "text/x-sls"),
        ("text/zig",),
        ("thrift",),
        ("ti", "thingsdb"),
        ("tid",),
        ("tnt",),
        ("todo.txt", "*.todotxt"),
        ("todotxt",),
        ("toml",),
        ("trac-wiki", "moin"),
        ("trafficscript", "rts"),
        ("treetop",),
        ("tsql", "t-sql"),
        ("turtle",),
        ("twig",),
        ("typescript", "ts"),
        ("typoscript",),
        ("typoscriptcssdata",),
        ("typoscripthtmldata",),
        ("ucode",),
        ("unicon",),
        ("unixconfig", "linuxconfig"),
        ("urbiscript",),
        ("usd", "usda"),
        ("vala", "vapi"),
        ("vb.net", "vbnet", "lobas", "oobas", "sobas"),
        ("vbscript",),
        ("vcl",),
        ("vclsnippets", "vclsnippet"),
        ("vctreestatus",),
        ("velocity",),
        ("verilog", "v"),
        ("vhdl",),
        ("vim",),
        ("wast", "wat"),
        ("wdiff",),
        ("webidl",),
        ("wgsl",),
        ("whiley",),
        ("wikitext", "mediawiki"),
        ("wowtoc",),
        ("wren",),
        ("x10", "xten"),
        ("xml",),
        ("xml+cheetah", "xml+spitfire"),
        ("xml+django", "xml+jinja"),
        ("xml+evoque",),
        ("xml+lasso",),
        ("xml+mako",),
        ("xml+myghty",),
        ("xml+php",),
        ("xml+ruby", "xml+erb"),
        ("xml+smarty",),
        ("xml+ul4",),
        ("xml+velocity",),
        ("xorg.conf",),
        ("xpp", "x++"),
        ("xquery", "xqy", "xq", "xql", "xqm"),
        ("xslt",),
        ("xtend",),
        ("xul+mozpreproc",),
        ("yaml",),
        ("yaml+jinja", "salt", "sls"),
        ("yang",),
        ("zeek", "bro"),
        ("zephir",),
        ("zig",),
        (),
        ),
    "ABAPLexer": (
    "AbnfLexer": (
    "ActionScript3Lexer": (
    "ActionScriptLexer": (
    "AdaLexer": (
    "AdlLexer": (
    "AgdaLexer": (
    "AheuiLexer": (
    "AlloyLexer": (
    "AmbientTalkLexer": (
    "AMDGPULexer": (
    "AmplLexer": (
    "Angular2HtmlLexer": (
    "Angular2Lexer": (
    "AntlrActionScriptLexer": (
    "AntlrCppLexer": (
    "AntlrCSharpLexer": (
    "AntlrJavaLexer": (
    "AntlrLexer": ("pip._vendor.pygments.lexers.parsers", "ANTLR", ("antlr",), (), ()),
    "AntlrObjectiveCLexer": (
    "AntlrPerlLexer": (
    "AntlrPythonLexer": (
    "AntlrRubyLexer": (
    "ApacheConfLexer": (
    "apdlexer": (
    "APLLexer": (
    "AppleScriptLexer": (
    "ArduinoLexer": (
    "ArrowLexer": (
    "ArturoLexer": (
    "AscLexer": (
    "AspectJLexer": (
    "AsymptoteLexer": (
    "AugeasLexer": (
    "AutohotkeyLexer": (
    "AutoItLexer": (
    "AwkLexer": (
    "BareLexer": (
    "BaseMakefileLexer": (
    "BashLexer": (
    "BashSessionLexer": (
    "BatchLexer": (
    "BBCBasicLexer": (
    "BBCodeLexer": (
    "BCLexer": ("pip._vendor.pygments.lexers.algebra", "BC", ("bc",), ("*.bc",), ()),
    "BddLexer": (
    "BefungeLexer": (
    "BerryLexer": (
    "BibTeXLexer": (
    "BlitzBasicLexer": (
    "BlitzMaxLexer": (
    "BnfLexer": (
    "BoaLexer": ("pip._vendor.pygments.lexers.boa", "Boa", ("boa",), ("*.boa",), ()),
    "BoogieLexer": (
    "BooLexer": (
    "BrainfuckLexer": (
    "BSTLexer": (
    "BugsLexer": (
    "Ca65Lexer": (
    "CadlLexer": (
    "CAmkESLexer": (
    "CapDLLexer": (
    "CapnProtoLexer": (
    "CarbonLexer": (
    "CbmBasicV2Lexer": (
    "CddlLexer": (
    "CeylonLexer": (
    "Cfengine3Lexer": (
    "ChaiscriptLexer": (
    "ChapelLexer": (
    "CharmciLexer": (
    "CheetahHtmlLexer": (
    "CheetahJavascriptLexer": (
    "CheetahLexer": (
    "CheetahXmlLexer": (
    "CirruLexer": (
    "ClayLexer": (
    "CleanLexer": (
    "CLexer": (
    "ClojureLexer": (
    "ClojureScriptLexer": (
    "CMakeLexer": (
    "CObjdumpLexer": (
    "CobolFreeformatLexer": (
    "CobolLexer": (
    "CoffeeScriptLexer": (
    "ColdfusionCFCLexer": (
    "ColdfusionHtmlLexer": (
    "ColdfusionLexer": (
    "Comal80Lexer": (
    "CommonLispLexer": (
    "ComponentPascalLexer": (
    "CoqLexer": (
    "CplintLexer": (
    "CppLexer": (
    "CppObjdumpLexer": (
    "CPSALexer": (
    "CrmshLexer": (
    "CrocLexer": (
    "CryptolLexer": (
    "CrystalLexer": (
    "CSharpAspxLexer": (
    "CSharpLexer": (
    "CsoundDocumentLexer": (
    "CsoundOrchestraLexer": (
    "CsoundScoreLexer": (
    "CssDjangoLexer": (
    "CssErbLexer": (
    "CssGenshiLexer": (
    "CssLexer": (
    "CssPhpLexer": (
    "CssSmartyLexer": (
    "CSSUL4Lexer": (
    "CudaLexer": (
    "CypherLexer": (
    "CythonLexer": (
    "DarcsPatchLexer": (
    "DartLexer": (
    "Dasm16Lexer": (
    "DaxLexer": ("pip._vendor.pygments.lexers.dax", "Dax", ("dax",), ("*.dax",), ()),
    "DebianControlLexer": (
    "DelphiLexer": (
    "DevicetreeLexer": (
    "DgLexer": (
    "DiffLexer": (
    "DjangoLexer": (
    "DLexer": (
    "DObjdumpLexer": (
    "DockerLexer": (
    "DtdLexer": (
    "DuelLexer": (
    "DylanConsoleLexer": (
    "DylanLexer": (
    "DylanLidLexer": (
    "EarlGreyLexer": (
    "EasytrieveLexer": (
    "EbnfLexer": (
    "ECLexer": (
    "ECLLexer": (
    "EiffelLexer": (
    "ElixirConsoleLexer": (
    "ElixirLexer": (
    "ElmLexer": (
    "ElpiLexer": (
    "EmacsLispLexer": (
    "EmailLexer": (
    "ErbLexer": (
    "ErlangLexer": (
    "ErlangShellLexer": (
    "EvoqueHtmlLexer": (
    "EvoqueLexer": (
    "EvoqueXmlLexer": (
    "ExeclineLexer": (
    "EzhilLexer": (
    "FactorLexer": (
    "FancyLexer": (
    "FantomLexer": (
    "FelixLexer": (
    "FennelLexer": (
    "FiftLexer": (
    "FishShellLexer": (
    "FlatlineLexer": (
    "FloScriptLexer": (
    "ForthLexer": (
    "FortranFixedLexer": (
    "FortranLexer": (
    "FoxProLexer": (
    "FreeFemLexer": (
    "FSharpLexer": (
    "FStarLexer": (
    "FuncLexer": (
    "FutharkLexer": (
    "GAPConsoleLexer": (
    "GAPLexer": (
    "GasLexer": (
    "GcodeLexer": (
    "GDScriptLexer": (
    "GenshiLexer": (
    "GenshiTextLexer": (
    "GettextLexer": (
    "GherkinLexer": (
    "GLShaderLexer": (
    "GnuplotLexer": (
    "GoLexer": (
    "GoloLexer": (
    "GoodDataCLLexer": (
    "GosuLexer": (
    "GosuTemplateLexer": (
    "GraphvizLexer": (
    "GroffLexer": (
    "GroovyLexer": (
    "GSQLLexer": (
    "HamlLexer": (
    "HandlebarsHtmlLexer": (
    "HandlebarsLexer": (
    "HaskellLexer": (
    "HaxeLexer": (
    "HexdumpLexer": (
    "HLSLShaderLexer": (
    "HsailLexer": (
    "HspecLexer": (
    "HtmlDjangoLexer": (
    "HtmlGenshiLexer": (
    "HtmlLexer": (
    "HtmlPhpLexer": (
    "HtmlSmartyLexer": (
    "HTMLUL4Lexer": (
    "HttpLexer": ("pip._vendor.pygments.lexers.textfmts", "HTTP", ("http",), (), ()),
    "HxmlLexer": (
    "HybrisLexer": (
    "HyLexer": (
    "IconLexer": (
    "IDLLexer": (
    "IdrisLexer": (
    "IgorLexer": (
    "Inform6Lexer": (
    "Inform6TemplateLexer": (
    "Inform7Lexer": (
    "IniLexer": (
    "IokeLexer": (
    "IoLexer": (
    "IrcLogsLexer": (
    "IsabelleLexer": (
    "JagsLexer": (
    "JasminLexer": (
    "JavaLexer": (
    "JavascriptDjangoLexer": (
    "JavascriptErbLexer": (
    "JavascriptGenshiLexer": (
    "JavascriptLexer": (
    "JavascriptPhpLexer": (
    "JavascriptSmartyLexer": (
    "JavascriptUL4Lexer": (
    "JclLexer": (
    "JLexer": ("pip._vendor.pygments.lexers.j", "J", ("j",), ("*.ijs",), ("text/x-j",)),
    "JMESPathLexer": (
    "JsgfLexer": (
    "JSLTLexer": (
    "JsonBareObjectLexer": (
    "JsonLdLexer": (
    "JsonLexer": (
    "JsonnetLexer": (
    "JspLexer": (
    "JuliaConsoleLexer": (
    "JuliaLexer": (
    "JuttleLexer": (
    "KalLexer": (
    "KconfigLexer": (
    "KernelLogLexer": (
    "KLexer": ("pip._vendor.pygments.lexers.q", "K", ("k",), ("*.k",), ()),
    "KokaLexer": (
    "KotlinLexer": (
    "KuinLexer": ("pip._vendor.pygments.lexers.kuin", "Kuin", ("kuin",), ("*.kn",), ()),
    "LassoCssLexer": (
    "LassoHtmlLexer": (
    "LassoJavascriptLexer": (
    "LassoLexer": (
    "LassoXmlLexer": (
    "LeanLexer": (
    "LessCssLexer": (
    "LighttpdConfLexer": (
    "LilyPondLexer": (
    "LimboLexer": (
    "LiquidLexer": (
    "LiterateAgdaLexer": (
    "LiterateCryptolLexer": (
    "LiterateHaskellLexer": (
    "LiterateIdrisLexer": (
    "LiveScriptLexer": (
    "LlvmLexer": (
    "LlvmMirBodyLexer": (
    "LlvmMirLexer": (
    "LogosLexer": (
    "LogtalkLexer": (
    "LSLLexer": (
    "LuaLexer": (
    "Macaulay2Lexer": (
    "MakefileLexer": (
    "MakoCssLexer": (
    "MakoHtmlLexer": (
    "MakoJavascriptLexer": (
    "MakoLexer": (
    "MakoXmlLexer": (
    "MaqlLexer": (
    "MarkdownLexer": (
    "MaskLexer": (
    "MasonLexer": (
    "MathematicaLexer": (
    "MatlabLexer": (
    "MatlabSessionLexer": (
    "MaximaLexer": (
    "MCFunctionLexer": (
    "MCSchemaLexer": (
    "MesonLexer": (
    "MIMELexer": (
    "MiniDLexer": (
    "MiniScriptLexer": (
    "MIPSLexer": (
    "ModelicaLexer": (
    "Modula2Lexer": (
    "MoinWikiLexer": (
    "MonkeyLexer": (
    "MonteLexer": (
    "MOOCodeLexer": (
    "MoonScriptLexer": (
    "MoselLexer": (
    "MozPreprocCssLexer": (
    "MozPreprocHashLexer": (
    "MozPreprocJavascriptLexer": (
    "MozPreprocPercentLexer": (
    "MozPreprocXulLexer": (
    "MqlLexer": (
    "MscgenLexer": (
    "MSDOSSessionLexer": (
    "MuPADLexer": (
    "MxmlLexer": (
    "MyghtyCssLexer": (
    "MyghtyHtmlLexer": (
    "MyghtyJavascriptLexer": (
    "MyghtyLexer": (
    "MyghtyXmlLexer": (
    "MySqlLexer": (
    "NasmLexer": (
    "NasmObjdumpLexer": (
    "NCLLexer": (
    "NemerleLexer": (
    "NesCLexer": (
    "NestedTextLexer": (
    "NewLispLexer": (
    "NewspeakLexer": (
    "NginxConfLexer": (
    "NimrodLexer": (
    "NitLexer": ("pip._vendor.pygments.lexers.nit", "Nit", ("nit",), ("*.nit",), ()),
    "NixLexer": (
    "NodeConsoleLexer": (
    "NotmuchLexer": (
    "NSISLexer": (
    "NumPyLexer": ("pip._vendor.pygments.lexers.python", "NumPy", ("numpy",), (), ()),
    "NuSMVLexer": (
    "ObjdumpLexer": (
    "ObjectiveCLexer": (
    "ObjectiveCppLexer": (
    "ObjectiveJLexer": (
    "OcamlLexer": (
    "OctaveLexer": (
    "OdinLexer": (
    "OmgIdlLexer": (
    "OocLexer": (
    "OpaLexer": (
    "OpenEdgeLexer": (
    "OutputLexer": (
    "PacmanConfLexer": (
    "PanLexer": ("pip._vendor.pygments.lexers.dsls", "Pan", ("pan",), ("*.pan",), ()),
    "ParaSailLexer": (
    "PawnLexer": (
    "PegLexer": (
    "Perl6Lexer": (
    "PerlLexer": (
    "PhixLexer": (
    "PhpLexer": (
    "PigLexer": (
    "PikeLexer": (
    "PkgConfigLexer": (
    "PlPgsqlLexer": (
    "PointlessLexer": (
    "PonyLexer": (
    "PortugolLexer": (
    "PostgresConsoleLexer": (
    "PostgresExplainLexer": (
    "PostgresLexer": (
    "PostScriptLexer": (
    "PovrayLexer": (
    "PowerShellLexer": (
    "PowerShellSessionLexer": (
    "PraatLexer": (
    "ProcfileLexer": (
    "PrologLexer": (
    "PromQLLexer": (
    "PropertiesLexer": (
    "ProtoBufLexer": (
    "PsyshConsoleLexer": (
    "PugLexer": (
    "PuppetLexer": (
    "PyPyLogLexer": (
    "Python2Lexer": (
    "Python2TracebackLexer": (
    "PythonConsoleLexer": (
    "PythonLexer": (
    "PythonTracebackLexer": (
    "PythonUL4Lexer": (
    "QBasicLexer": (
    "QLexer": ("pip._vendor.pygments.lexers.q", "Q", ("q",), ("*.q",), ()),
    "QlikLexer": (
    "QmlLexer": (
    "QVToLexer": (
    "RacketLexer": (
    "RagelCLexer": (
    "RagelCppLexer": (
    "RagelDLexer": (
    "RagelEmbeddedLexer": (
    "RagelJavaLexer": (
    "RagelLexer": ("pip._vendor.pygments.lexers.parsers", "Ragel", ("ragel",), (), ()),
    "RagelObjectiveCLexer": (
    "RagelRubyLexer": (
    "RawTokenLexer": (
    "RConsoleLexer": (
    "RdLexer": (
    "ReasonLexer": (
    "RebolLexer": (
    "RedcodeLexer": (
    "RedLexer": (
    "RegeditLexer": (
    "ResourceLexer": (
    "RexxLexer": (
    "RhtmlLexer": (
    "RideLexer": (
    "RitaLexer": (
    "RNCCompactLexer": (
    "RoboconfGraphLexer": (
    "RoboconfInstancesLexer": (
    "RobotFrameworkLexer": (
    "RPMSpecLexer": (
    "RqlLexer": (
    "RslLexer": (
    "RstLexer": (
    "RtsLexer": (
    "RubyConsoleLexer": (
    "RubyLexer": (
    "RustLexer": (
    "SarlLexer": (
    "SASLexer": (
    "SassLexer": (
    "SaviLexer": (
    "ScalaLexer": (
    "ScamlLexer": (
    "ScdocLexer": (
    "SchemeLexer": (
    "ScilabLexer": (
    "ScssLexer": (
    "SedLexer": (
    "ShenLexer": (
    "ShExCLexer": (
    "SieveLexer": (
    "SilverLexer": (
    "SingularityLexer": (
    "SlashLexer": (
    "SLexer": (
    "SlimLexer": (
    "SlurmBashLexer": (
    "SmaliLexer": (
    "SmalltalkLexer": (
    "SmartGameFormatLexer": (
    "SmartyLexer": (
    "SmithyLexer": (
    "SMLLexer": (
    "SNBTLexer": (
    "SnobolLexer": (
    "SnowballLexer": (
    "SolidityLexer": (
    "SophiaLexer": (
    "SourcePawnLexer": (
    "SourcesListLexer": (
    "SparqlLexer": (
    "SpiceLexer": (
    "SqliteConsoleLexer": (
    "SqlJinjaLexer": (
    "SqlLexer": (
    "SquidConfLexer": (
    "SrcinfoLexer": (
    "SspLexer": (
    "StanLexer": (
    "StataLexer": (
    "SuperColliderLexer": (
    "SwiftLexer": (
    "SwigLexer": (
    "SystemVerilogLexer": (
    "Tads3Lexer": (
    "TalLexer": (
    "TAPLexer": (
    "TasmLexer": (
    "TclLexer": (
    "TcshLexer": (
    "TcshSessionLexer": (
    "TealLexer": (
    "TeaTemplateLexer": (
    "TeraTermLexer": (
    "TermcapLexer": (
    "TerminfoLexer": (
    "TerraformLexer": (
    "TexLexer": (
    "TextLexer": (
    "ThingsDBLexer": (
    "ThriftLexer": (
    "TiddlyWiki5Lexer": (
    "TlbLexer": ("pip._vendor.pygments.lexers.tlb", "Tl-b", ("tlb",), ("*.tlb",), ()),
    "TNTLexer": (
    "TodotxtLexer": (
    "TOMLLexer": (
    "TransactSqlLexer": (
    "TreetopLexer": (
    "TurtleLexer": (
    "TwigHtmlLexer": (
    "TwigLexer": (
    "TypeScriptLexer": (
    "TypoScriptCssDataLexer": (
    "TypoScriptHtmlDataLexer": (
    "TypoScriptLexer": (
    "UcodeLexer": (
    "UL4Lexer": ("pip._vendor.pygments.lexers.ul4", "UL4", ("ul4",), ("*.ul4",), ()),
    "UniconLexer": (
    "UnixConfigLexer": (
    "UrbiscriptLexer": (
    "UsdLexer": (
    "ValaLexer": (
    "VbNetAspxLexer": (
    "VbNetLexer": (
    "VBScriptLexer": (
    "VCLLexer": (
    "VCLSnippetLexer": (
    "VCTreeStatusLexer": (
    "VelocityHtmlLexer": (
    "VelocityLexer": (
    "VelocityXmlLexer": (
    "VerilogLexer": (
    "VGLLexer": ("pip._vendor.pygments.lexers.dsls", "VGL", ("vgl",), ("*.rpf",), ()),
    "VhdlLexer": (
    "VimLexer": (
    "WatLexer": (
    "WDiffLexer": (
    "WebIDLLexer": (
    "WgslLexer": (
    "WhileyLexer": (
    "WikitextLexer": (
    "WoWTocLexer": (
    "WrenLexer": (
    "X10Lexer": (
    "XmlDjangoLexer": (
    "XmlErbLexer": (
    "XmlLexer": (
    "XmlPhpLexer": (
    "XmlSmartyLexer": (
    "XMLUL4Lexer": (
    "XorgLexer": (
    "XppLexer": (
    "XQueryLexer": (
    "XsltLexer": (
    "XtendLexer": (
    "XtlangLexer": (
    "YamlJinjaLexer": (
    "YamlLexer": (
    "YangLexer": (
    "ZeekLexer": (
    "ZephirLexer": (
    "ZigLexer": (
    ),
# -*- coding: utf-8 -*-
# Automatically generated by scripts/gen_mapfiles.py.
# DO NOT EDIT BY HAND; run `tox -e mapfiles` instead.
}
LEXERS = {

pass
