
        "method": "Extensions.clearStorageItems",
        "method": "Extensions.getStorageItems",
        "method": "Extensions.loadUnpacked",
        "method": "Extensions.removeStorageItems",
        "method": "Extensions.setStorageItems",
        "params": params,
        params["keys"] = [i for i in keys]
        return cls(json)
        return self.value
    """
    :param id_: ID of extension.
    :param keys: *(Optional)* Keys to retrieve.
    :param keys: Keys to remove.
    :param path: Absolute file path.
    :param storage_area: StorageArea to remove data from.
    :param storage_area: StorageArea to retrieve data from.
    :param storage_area: StorageArea to set data in.
    :param values: Values to set.
    :returns:
    :returns: Extension id.
    @classmethod
    }
    Clears extension storage in the given ``storageArea``.
    cmd_dict: T_JSON_DICT = {
    def __init__(self, *args, **kwargs): pass
    def from_json(cls, json):
    def to_json(self):
    flag is set.
    Gets data from extension storage in the given ``storageArea``. If ``keys`` is
    has been installed. Available if the client is connected using the
    id_: str, storage_area: StorageArea
    id_: str, storage_area: StorageArea, keys: list[str]
    id_: str, storage_area: StorageArea, keys: list[str] | None = None
    id_: str, storage_area: StorageArea, values: dict
    if keys is not None:
    Installs an unpacked extension from the filesystem similar to
    json = yield cmd_dict
    --load-extension CLI flags. Returns extension ID once the extension
    LOCAL = "local"
    MANAGED = "managed"
    params: T_JSON_DICT = dict()
    params["id"] = id_
    params["keys"] = [i for i in keys]
    params["path"] = path
    params["storageArea"] = storage_area.to_json()
    params["values"] = values
    --remote-debugging-pipe flag and the --enable-unsafe-extension-debugging
    Removes ``keys`` from extension storage in the given ``storageArea``.
    return dict(json["data"])
    return str(json["id"])
    SESSION = "session"
    Sets ``values`` in extension storage in the given ``storageArea``. The provided ``values``
    specified, these are used to filter the result.
    Storage areas.
    SYNC = "sync"
    will be merged with existing values in the storage area.
#
# CDP domain: Extensions (experimental)
# changes, edit the generator and regenerate all of the modules.
# DO NOT EDIT THIS FILE!
# This file is generated from the CDP specification. If you need to make
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, dict]:
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
class StorageArea:
def clear_storage_items(
def get_storage_items(
def load_unpacked(path: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]:
def remove_storage_items(
def set_storage_items(
from .util import T_JSON_DICT
from __future__ import annotations
import typing
