repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: fix-byte-order-marker
        stages: [manual]
      - id: trailing-whitespace
        stages: [manual]
      - id: end-of-file-fixer
        stages: [manual]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.10
        stages: [manual]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.7.4  # ✅ 존재하는 안정 버전
    hooks:
      - id: pylint
        args: [--disable=R,C]
        language_version: python3.10
        stages: [manual]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        language_version: python3.10
        stages: [manual]
