
    -----
    ----------
                            f"{fun.__name__}() got multiple values for "
                            f"argument now known as `{new_name}`"
                            f"deprecated and replaced by `{new_name}`. "
                            f"in NumPy {end_version}."
                            f"Support for `{old_name}` will be removed "
                            f"Use of keyword argument `{old_name}` is "
                        )
                        end_version = ".".join(end_version)
                        end_version = dep_version.split(".")
                        end_version[1] = str(int(end_version[1]) + 2)
                        msg = (
                        raise TypeError(msg)
                        warnings.warn(msg, DeprecationWarning, stacklevel=2)
                    if dep_version:
                    if new_name in kwargs:
                    kwargs[new_name] = kwargs.pop(old_name)
                if old_name in kwargs:
            __tracebackhide__ = True  # Hide traceback for py.test
            for old_name, new_name in zip(old_names, new_names):
            func.__module__ = module
            pass
            return fun(*args, **kwargs)
        @functools.wraps(fun)
        @set_module('numpy')
        assert example.__module__ == 'numpy'
        def example():
        def wrapper(*args, **kwargs):
        if module is not None:
        New names of parameters
        Old names of parameters
        return func
        return wrapper
        support for the old parameter will be removed in version 'X.Y+2.Z'
        Version of NumPy in which old parameter was deprecated in the format
        'X.Y.Z'. If supplied, the deprecation message will indicate that
    """
    """Private decorator for overriding __module__ on a function or class.
    a DeprecationWarning if `dep_version` is provided, and behave as usual
    After decoration, the function behaves as follows:
    Apply the decorator generated by `_rename_parameter` to functions with a
    def decorator(fun):
    def decorator(func):
    dep_version : str, optional
    DeprecationWarning if `dep_version` is provided, and raise the appropriate
    Example usage::
    Generate decorator for backward-compatible keyword renaming.
    If both old and new parameters are passed into the function, raise a
    If only the new parameter is passed into the function, behave as usual.
    If only the old parameter is passed into the function (as a keyword), raise
    new_name : list of str
    Notes
    old_names : list of str
    otherwise.
    Parameters
    renamed parameter to maintain backward-compatibility.
    return decorator
    TypeError (function got multiple values for argument).
    Untested with functions that accept *args. Probably won't work as written.
"""
def _rename_parameter(old_names, new_names, dep_version=None):
def set_module(module):
Everything in here must be self-contained so that it can be
If a utility requires the import of NumPy, it probably belongs
import functools
import warnings
imported anywhere else without creating circular imports.
in ``numpy._core``.
rest of NumPy.
This is a module for defining private helpers which do not depend on the
